[package]
name = "pinentry-cadenza"
authors = ["municorn <municorn@musicaloft.com>"]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.102"
iced = { version = "0.14", features = ["smol"] }
iced_layershell = "0.15"
secrecy = "0.10"
smol = "2.0.2"
zeroize = "1"
